server:
    # IP address (recommended: do not use 'localhost', use ip address)
    addr: '127.0.0.1'
    port: '8053'

# directory where store statistic data (end must be /)
stats-file: '/tmp/'

# email error setting
email:
    # allow email for critical errors (boolean)
    allow: true
    # fake email name | system mail name
    from: 'kresd-serverXX@<fake domain>'
    # real email
    to:   '<name>@<domain>'
